#!/bin/sh -l
#SBATCH --partition=Apus
#SBATCH -J test_neb
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=96
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00
#SBATCH --mem=96G     

module load vasp/6.4.3
echo "Running on node: $(hostname)"
mpirun -np 8 python dft-gp-neb.py > log-neb
