#!/bin/bash

#SBATCH --partition=Apus
#SBATCH -J h2s-gp-dot
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=96
#SBATCH --cpus-per-task=1
#SBATCH --time=72:00:00
#SBATCH --mem=96G     

echo "Start Time : $(date)"
start_time=$(date +%s)
mpirun python test_mpi.py > log-neb.dat
end_time=$(date +%s)
run_time=$((end_time - start_time))
echo "Total runtime: $run_time seconds"
